---
- hosts: localhost
  connection: local

  vars:
    homebrew_installed_packages:
      - ansible
      - ansible-lint
      - autoconf
      - automake
      - awscli
      - bash
      - cmake
      - cowsay
      - dos2unix
      - ffmpeg
      - gcc
      - git
      - git-lfs
      - htop-osx
      - java
      - jp2a
      - kubernetes-cli
      - md5sha1sum
      - molecule
      - nacl
      - nmap
      - openssh
      - openssl
      - openssl@1.1
      - pinentry-mac
      - pngout
      - pre-commit
      - pwgen
      - rpm
      - ruby
      - saml2aws
      - unix2dos
      - wget
      - yamllint
      - zsh
    homebrew_taps:
      - hashicorp/tap
      - homebrew/cask-fonts
      - jonof/kenutils
      - versent/homebrew-taps
    homebrew_cask_apps:
      - 1password
      - alfred
      - amazon-chime
      - bartender
      - blueharvest
      - boinc
      - brave-browser
      - caffeine
      - cocktail
      - cyberduck
      - dash
      - divvy
      - firefox
      - flux
      - font-lato
      - font-mononoki
      - font-mononoki-nerd-font
      - font-source-code-pro
      - font-source-sans-3
      - gimp
      - gpg-suite
      - hazel
      - hex-fiend
      - imageoptim
      - istat-menus
      - iterm2
      - karabiner-elements
      - keepassx
      - libreoffice
      - microsoft-auto-update
      - microsoft-azure-storage-explorer
      - microsoft-excel
      - microsoft-outlook
      - microsoft-powerpoint
      - microsoft-remote-desktop
      - microsoft-teams
      - microsoft-word
      - onedrive
      - rescuetime
      - send-to-kindle
      - skitch
      - smartgit
      - smartsynchronize
      - sublime-text
      - via
      - yubico-authenticator
      - yubico-yubikey-manager

  roles:
    - finder
    - macos
    - screensaver
    - geerlingguy.mac.homebrew
    - role: smartgit
      smartgit_user_home: /Users/david.norman
    - bin
    - zsh
    - motd
    - hitrust
    - ansible
    - cowsay
