---
- hosts: localhost
  connection: local

  vars:
    homebrew_installed_packages:
      - ansible
      - ansible-lint
      - automake
      - awscli
      - azure-cli
      - bitwarden-cli
      - cmake
      - coreutils
      - derailed/k9s/k9s
      - docker
      - docker-buildx
      - dos2unix
      - ffmpeg
      - gh
      - git
      - git-lfs
      - git-sizer
      - glab
      - hashicorp/tap/terraform
      - htop
      - jq
      - jp2a
      - kubernetes-cli
      - llama.cpp
      - md5sha1sum
      - nmap
      - openjdk
      - openssh
      - pinentry-mac
      - pipx
      - pngout
      - poppler
      - pre-commit
      - pwgen
      - python@3.12
      - ruby
      - saml2aws
      - slackdump
      - sslscan
      - swaks
      - terraform-docs
      - testssl
      - tflint
      - trufflehog
      - wget
      - wireguard-tools
      - yamllint
      - zsh
    homebrew_taps:
      - derailed/k9s
      - hashicorp/tap
      - jonof/kenutils
      - versent/homebrew-taps
    homebrew_cask_apps:
      - 1password
      - alfred
      - amazon-chime
      - bartender
      - blueharvest
      - brave-browser
      - claude
      - cyberduck
      - dash
      - divvy
      - firefox
      - flux
      - flux-app
      - font-lato
      - font-mononoki
      - font-mononoki-nerd-font
      - font-source-code-pro
      - font-source-sans-3
      - gimp
      - gpg-suite
      - hazel
      - hex-fiend
      - imageoptim
      - istat-menus
      - iterm2
      - karabiner-elements
      - lm-studio
      - microsoft-auto-update
      - microsoft-excel
      - microsoft-outlook
      - microsoft-powerpoint
      - microsoft-teams
      - microsoft-word
      - onedrive
      - rescuetime
      - send-to-kindle
      - skitch
      - smartgit
      - smartsynchronize
      - sublime-text
      - yubico-authenticator

  roles:
    - finder
    - macos
    - screensaver
    - geerlingguy.mac.homebrew
    - role: smartgit
      smartgit_user_home: /Users/david.norman
    - bin
    - zsh
    - motd
    - hitrust
    - ansible
    - cowsay
