---

- name: Whitelist task profiling.
  community.general.files.ini_file:
    path: ~/.ansible.cfg
    section: defaults
    option: callback_whitelist
    value: profile_tasks,timer
    mode: 0644

- name: Omit skipped tasks from output.
  community.general.files.ini_file:
    path: ~/.ansible.cfg
    section: defaults
    option: display_skipped_hosts
    value: no
    mode: 0644
