---

- name: Disable sensitive and senseless swipe-based navigation.
  osx_defaults:
    domain: com.google.Chrome
    key: AppleEnableSwipeNavigateWithScrolls
    type: bool
    value: false
    state: present
